name = "cf-worker-backend"
main = "dist/index.js"
compatibility_date = "2024-04-20"
compatibility_flags = ["nodejs_compat"]
# 添加帳戶 ID
account_id = "4f25c0c4400bee3a338905458f5423c3" # 請替換為您想使用的帳戶 ID

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "stock_orders"
database_id = "30dc188e-9a49-4ee4-bd69-a63de46727a9" # 已創建的數據庫 ID

# 環境變數
[vars]
TWSE_API_BASE = "https://openapi.twse.com.tw"

# 開發環境設定
[env.dev]
vars = { ENVIRONMENT = "development" }

# 生產環境設定
[env.production]
vars = { ENVIRONMENT = "production" }

# 簡化路由配置，使用單純的字符串格式
routes = ["/api/*"]
