name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # 自動部署來源分支
  workflow_dispatch: # ✅ 新增手動部署選項
    inputs:
      environment:
        description: "部署環境"
        required: false
        default: "preview"

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 定義環境變數
    env:
      NODE_ENV: production
      NITRO_PRESET: cloudflare-pages

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 解決 Rollup 依賴問題
      - name: Setup Rollup WebAssembly
        run: |
          # 刪除舊的文件
          rm -rf node_modules package-lock.json || true

          # 修改 package.json 改為只使用 wasm 版本的 rollup
          cat <<EOF > temp-fix.js
          const fs = require('fs');
          const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));

          // 添加 @rollup/wasm-node 到 devDependencies
          packageJson.devDependencies = packageJson.devDependencies || {};
          packageJson.devDependencies['@rollup/wasm-node'] = '^4.13.0';

          // 確保有 resolutions 區塊
          packageJson.resolutions = packageJson.resolutions || {};
          packageJson.resolutions['rollup'] = 'npm:@rollup/wasm-node';

          // 修改 build 腳本，跳過 vercel-build-prepare.js
          packageJson.scripts.build = 'nuxt build';
          packageJson.scripts.postinstall = 'nuxt prepare';

          // 刪除不必要的 scripts
          delete packageJson.scripts.preinstall;

          fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));
          EOF

          node temp-fix.js
          rm temp-fix.js

      - name: Install Dependencies
        run: npm install
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      # 先使用 generate 確保生成靜態文件
      - name: Generate Static Files
        run: npm run generate
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NUXT_APP_BASE_URL: "/"
          CF_PAGES: true
          NITRO_PRESET: cloudflare-pages

      # 只在 generate 失敗時嘗試 build
      - name: Build Nuxt 3 Project (if needed)
        if: ${{ failure() }}
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NUXT_APP_BASE_URL: "/"
          CF_PAGES: true
          NITRO_PRESET: cloudflare-pages

      - name: Debug Output Directory
        run: |
          ls -la
          echo "== .output directory =="
          ls -la .output || echo "No .output directory"
          echo "== .output/public directory =="
          ls -la .output/public || echo "No .output/public directory"
          echo "== dist directory =="
          ls -la dist || echo "No dist directory"
          echo "== .nuxt directory =="
          ls -la .nuxt || echo "No .nuxt directory"

      # 檢查構建輸出並處理
      - name: Prepare Output Directory
        run: |
          # 如果 .output/public 目錄不存在，嘗試從 dist 目錄複製
          if [ ! -d ".output/public" ]; then
            echo "No .output/public directory, checking alternatives..."
            
            # 先嘗試創建目錄
            mkdir -p .output/public
            
            if [ -d "dist" ]; then
              echo "Found dist directory, using it as output"
              cp -r dist/* .output/public/
            elif [ -d ".output/server/public" ]; then
              echo "Found .output/server/public directory, using it"
              cp -r .output/server/public/* .output/public/
            else
              echo "Creating empty .output/public directory with placeholder"
              echo "<html><body><h1>Build Failed</h1><p>Please check the logs.</p></body></html>" > .output/public/index.html
            fi
          fi

          # 確保 .output/public 目錄中至少有一個 index.html 文件
          if [ ! -f ".output/public/index.html" ]; then
            echo "<html><body><h1>Build Failed</h1><p>No index.html found. Please check the logs.</p></body></html>" > .output/public/index.html
          fi

          # 再次檢查輸出目錄
          echo "Final output directory contents:"
          ls -la .output/public

      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .output/public
          # 使用最新的 wrangler 版本
          wranglerVersion: 4
